
#import <Foundation/Foundation.h>

#ifndef NGNCONFIGURATIONENTRY_H
#define NGNCONFIGURATIONENTRY_H

#define PCSCF_DISCOVERY_DNS_SRV @"DNS_NAPTR_SRV"

#define GENERAL_ACCESS_CONTACTS_LIST_NOT_ALLOW 0
#define GENERAL_ACCESS_CONTACTS_LIST_ALLOW 1

// General
#define GENERAL_AUTOSTART @"GENERAL_AUTOSTART"
#define GENERAL_SHOW_WELCOME_SCREEN @"GENERAL_SHOW_WELCOME_SCREEN"
#define GENERAL_FULL_SCREEN_VIDEO @"GENERAL_FULL_SCREEN_VIDEO"
#define GENERAL_USE_FFC @"GENERAL_USE_FFC"
#define GENERAL_INTERCEPT_OUTGOING_CALLS @"GENERAL_INTERCEPT_OUTGOING_CALLS"
#define GENERAL_VIDEO_FLIP @"GENERAL_VIDEO_FLIP"
#define GENERAL_AUDIO_PLAY_LEVEL @"GENERAL_AUDIO_PLAY_LEVEL"
#define GENERAL_ENUM_DOMAIN @"GENERAL_ENUM_DOMAIN"
#define GENERAL_SEND_DEVICE_INFO @"GENERAL_SEND_DEVICE_INFO"
#define GENERAL_ACCESS_CONTACTS_LIST @"GENERAL_ACCESS_CONTACTS_LIST"
#define GENERAL_LANDS_CALL_ENABLE @"GENERAL_LANDS_CALL_ENABLE"
#define GENERAL_CALLBACK_ENABLE @"GENERAL_CALLBACK_ENABLE"
#define GENERAL_INNET_CALL_ENABLE @"GENERAL_INNET_CALL_ENABLE"
#define GENERAL_PHONE_CALL_ENABLE @"GENERAL_PHONE_CALL_ENABLE"
#define GENERAL_DIAL_TONE_ENABLE @"GENERAL_DIAL_TONE_ENABLE"
#define GENERAL_MAKET_TYPE @"GENERAL_MAKET_TYPE"
#define GENERAL_ISSHOWSHAKETOSIGNINTIPS @"GENERAL_ISSHOWSHAKETOSIGNINTIPS"
#define GENERAL_NeverPromptHappyToShakeAnnounce @"GENERAL_NeverPromptHappyToShakeAnnounce"
#define GENERAL_LAST_GET_SYS_NOTIFY_TIME @"GENERAL_LAST_GET_SYS_NOTIFY_TIME"
#define GENERAL_FIRST_TIME_DIAL_VIA_CELL_PHONE @"GENERAL_FIRST_TIME_DIAL_VIA_CELL_PHONE"
#define GENERAL_ISSHOWSHAKETOWALLPOINTTIPS @"GENERAL_ISSHOWSHAKETOWALLPOINTTIPS"
#define GENERAL_NEEDTORELOADDATA @"GENERAL_NEEDTORELOADDATA"
#define GENERAL_ISHIDDENANNOUNCEONGAINCOUPON @"GENERAL_ISHIDDENANNOUNCEONGAINCOUPON"
#define GENERAL_LASTCHECKVERSIONDATE @"GENERAL_LASTCHECKVERSIONDATE"
#define GENERAL_TimeIntervalWithServ @"GENERAL_TimeIntervalWithServ"
#define GENERAL_CONTACT_MD5_STRING @"GENERAL_CONTACT_MD5_STRING"
#define GENERAL_IMSERVER_ADDR        @"GENERAL_IMSERVER_ADDR"        //IM服务器地址
#define GENERAL_IMSERVER_PORT_HTTP   @"GENERAL_IMSERVER_PORT_HTTP"   //IM服务器HTTP端口
#define GENERAL_IMSERVER_PORT        @"GENERAL_IMSERVER_PORT"        //IM服务器XMPP端口

// Identity
#define IDENTITY_DISPLAY_NAME @"identity_display_name"
#define IDENTITY_IMPU @"identity_impu"
#define IDENTITY_IMPI @"identity_impi"
#define IDENTITY_PASSWORD @"identity_password"

// Network
#define NETWORK_REGISTRATION_TIMEOUT @"NETWORK_REGISTRATION_TIMEOUT"
#define NETWORK_REALM @"NETWORK_REALM"
#define NETWORK_USE_WIFI @"NETWORK_USE_WIFI"
#define NETWORK_USE_3G @"NETWORK_USE_3G"
#define NETWORK_USE_EARLY_IMS @"NETWORK_USE_EARLY_IMS"
#define NETWORK_IP_VERSION @"NETWORK_IP_VERSION"
#define NETWORK_PCSCF_DISCOVERY_USE_DNS @"NETWORK_PCSCF_DISCOVERY_USE_DNS"
#define NETWORK_PCSCF_DISCOVERY_USE_DHCP @"NETWORK_PCSCF_DISCOVERY_USE_DHCP"
#define NETWORK_PCSCF_HOST @"NETWORK_PCSCF_HOST"
#define NETWORK_PCSCF_PORT @"NETWORK_PCSCF_PORT"
#define NETWORK_BACKUP_PCSCF_HOST @"NETWORK_BACKUP_PCSCF_HOST"
#define NETWORK_BACKUP_PCSCF_PORT @"NETWORK_BACKUP_PCSCF_PORT"
#define NETWORK_PCSCF_REG_HOST @"NETWORK_PCSCF_REG_HOST"
#define NETWORK_PCSCF_REG_PORT @"NETWORK_PCSCF_REG_PORT"
#define NETWORK_USE_SIGCOMP @"NETWORK_USE_SIGCOMP"
#define NETWORK_TRANSPORT @"NETWORK_TRANSPORT"

// Account
#define ACCOUNT_REFEREE @"account_referee"
#define ACCOUNT_LOCALNUM @"account_localnum"
#define ACCOUNT_NAME @"account_name"
#define ACCOUNT_NICKNAME @"account_nickname"
#define ACCOUNT_GENDER @"account_gender"
#define ACCOUNT_BIRTHDATE @"account_birthdate"
#define ACCOUNT_EMAIL @"account_email"
#define ACCOUNT_QQ @"account_qq"
#define ACCOUNT_SINAWEIBO @"account_sinaweibo"
#define ACCOUNT_LEVEL @"account_level"
#define ACCOUNT_CLOSETIP @"ACCOUNT_CLOSETIP"
#define ACCOUNT_THUMBNAIL @"account_thumbnail"

// NAT Traversal
#define NATT_HACK_AOR @"NATT_HACK_AOR"
#define NATT_HACK_AOR_TIMEOUT @"NATT_HACK_AOR_TIMEOUT"
#define NATT_USE_STUN @"NATT_USE_STUN"
#define NATT_USE_ICE @"NATT_USE_ICE"
#define NATT_USE_STUN_DISCO @"NATT_USE_STUN_DISCO"
#define NATT_STUN_SERVER @"NATT_STUN_SERVER"
#define NATT_STUN_PORT @"NATT_STUN_PORT"

// QoS
#define QOS_PRECOND_BANDWIDTH @"QOS_PRECOND_BANDWIDTH"
#define QOS_PRECOND_STRENGTH @"QOS_PRECOND_STRENGTH"
#define QOS_PRECOND_TYPE @"QOS_PRECOND_TYPE"
#define QOS_REFRESHER @"QOS_REFRESHER"
#define QOS_SIP_CALLS_TIMEOUT @"QOS_SIP_CALLS_TIMEOUT"
#define QOS_SIP_SESSIONS_TIMEOUT @"QOS_SIP_SESSIONS_TIMEOUT"
#define QOS_USE_SESSION_TIMERS @"QOS_USE_SESSION_TIMERS"


// Media
#define MEDIA_CODECS @"MEDIA_CODECS"
#define MEDIA_CODEC_USE_G722 @"MEDIA_CODEC_USE_G722"
#define MEDIA_CODEC_USE_G729AB @"MEDIA_CODEC_USE_G729AB"
#define MEDIA_CODEC_USE_AMR_NB_OA @"MEDIA_CODEC_USE_AMR_NB_OA"
#define MEDIA_CODEC_USE_AMR_NB_BE @"MEDIA_CODEC_USE_AMR_NB_BE"
#define MEDIA_CODEC_USE_GSM @"MEDIA_CODEC_USE_GSM"
#define MEDIA_CODEC_USE_PCMA @"MEDIA_CODEC_USE_PCMA"
#define MEDIA_CODEC_USE_PCMU @"MEDIA_CODEC_USE_PCMU"
#define MEDIA_CODEC_USE_SPEEX_NB @"MEDIA_CODEC_USE_SPEEX_NB"
#define MEDIA_CODEC_USE_SPEEX_WB @"MEDIA_CODEC_USE_SPEEX_WB"
#define MEDIA_CODEC_USE_SPEEX_UWB @"MEDIA_CODEC_USE_SPEEX_UWB"
#define MEDIA_CODEC_USE_VP8 @"MEDIA_CODEC_USE_VP8"
#define MEDIA_CODEC_USE_H263 @"MEDIA_CODEC_USE_H263"
#define MEDIA_CODEC_USE_H263P @"MEDIA_CODEC_USE_H263P"
#define MEDIA_CODEC_USE_H264BP10 @"MEDIA_CODEC_USE_H264BP10"
#define MEDIA_CODEC_USE_H264BP20 @"MEDIA_CODEC_USE_H264BP20"
#define MEDIA_CODEC_USE_H264BP30 @"MEDIA_CODEC_USE_H264BP30"
#define MEDIA_CODEC_USE_THEORA @"MEDIA_CODEC_USE_THEORA"
#define MEDIA_CODEC_USE_MP4VES @"MEDIA_CODEC_USE_MP4VES"
#define MEDIA_AUDIO_RESAMPLER_QUALITY @"MEDIA_AUDIO_RESAMPLER_QUALITY"
#define MEDIA_AUDIO_CONSUMER_GAIN @"MEDIA_AUDIO_CONSUMER_GAIN"
#define MEDIA_AUDIO_PRODUCER_GAIN @"MEDIA_AUDIO_PRODUCER_GAIN"
#define MEDIA_AUDIO_CONSUMER_ATTENUATION @"MEDIA_AUDIO_CONSUMER_ATTENUATION"
#define MEDIA_AUDIO_PRODUCER_ATTENUATION @"MEDIA_AUDIO_PRODUCER_ATTENUATION"

// Security
#define SECURITY_IMSAKA_AMF @"SECURITY_IMSAKA_AMF"
#define SECURITY_IMSAKA_OPID @"SECURITY_IMSAKA_OPID"
#define SECURITY_SSL_FILE_KEY_PRIV @"SECURITY_SSL_FILE_KEY_PRIV"
#define SECURITY_SSL_FILE_KEY_PUB @"SECURITY_SSL_FILE_KEY_PUB"
#define SECURITY_SSL_FILE_KEY_CA @"SECURITY_SSL_FILE_KEY_CA"
#define SECURITY_DEVICE_TOKEN @"SECURITY_DEVICE_TOKEN"

// XCAP
#define XCAP_PASSWORD @"XCAP_PASSWORD"
#define XCAP_USERNAME @"XCAP_USERNAME"
#define XCAP_ENABLED @"XCAP_ENABLED"
#define XCAP_XCAP_ROOT @"XCAP_XCAP_ROOT"

// RCS (Rich Communication Suite)
#define RCS_AVATAR_PATH @"RCS_AVATAR_PATH"
#define RCS_USE_BINARY_SMS @"RCS_USE_BINARY_SMS"
#define RCS_CONF_FACT @"RCS_CONF_FACT"
#define RCS_FREE_TEXT @"RCS_FREE_TEXT"
#define RCS_HACK_SMS @"RCS_HACK_SMS"
#define RCS_USE_MSRP_FAILURE @"RCS_USE_MSRP_FAILURE"
#define RCS_USE_MSRP_SUCCESS @"RCS_USE_MSRP_SUCCESS"
#define RCS_USE_MWI @"RCS_USE_MWI"
#define RCS_USE_OMAFDR @"RCS_USE_OMAFDR"
#define RCS_USE_PARTIAL_PUB @"RCS_USE_PARTIAL_PUB"
#define RCS_USE_PRESENCE @"RCS_USE_PRESENCE"
#define RCS_USE_RLS @"RCS_USE_RLS"
#define RCS_SMSC @"RCS_SMSC"
#define RCS_STATUS  @"RCS_STATUS"
#define RCS_AUTO_ACCEPT_PAGER_MODE_IM	@"RCS_AUTO_ACCEPT_PAGER_MODE_IM"


//
//      Default values
//

// General
#define DEFAULT_GENERAL_SHOW_WELCOME_SCREEN YES
#define DEFAULT_GENERAL_FULL_SCREEN_VIDEO YES
#define DEFAULT_GENERAL_INTERCEPT_OUTGOING_CALLS YES
#define DEFAULT_GENERAL_USE_FFC YES
#define DEFAULT_GENERAL_FLIP_VIDEO NO
#define DEFAULT_GENERAL_AUTOSTART YES
#define DEFAULT_GENERAL_AUDIO_PLAY_LEVEL 0.25f
#define DEFAULT_GENERAL_ENUM_DOMAIN @"e164.org"
#define DEFAULT_GENERAL_SEND_DEVICE_INFO	NO
#define DEFAULT_GENERAL_ACCESS_CONTACTS_LIST -1
#define DEFAULT_GENERAL_LANDS_CALL_ENABLE YES
#define DEFAULT_GENERAL_CALLBACK_ENABLE YES
#define DEFAULT_GENERAL_INNET_CALL_ENABLE NO
#define DEFAULT_GENERAL_PHONE_CALL_ENABLE NO

#define DEFAULT_GENERAL_DIAL_TONE_ENABLE YES
#define DEFAULT_GENERAL_MAKET_TYPE 0
#define DEFAULT_GENERAL_ISSHOWSHAKETOSIGNINTIPS NO
#define DEFAULT_GENERAL_NeverPromptHappyToShakeAnnounce NO
#define DEFAULT_GENERAL_LAST_GET_SYS_NOTIFY_TIME 0
#define DEFAULT_GENERAL_FIRST_TIME_DIAL_VIA_CELL_PHONE YES

//      Identity
#define DEFAULT_IDENTITY_DISPLAY_NAME @"YunTong"
#define DEFAULT_IDENTITY_IMPU @"0000"
#define DEFAULT_IDENTITY_IMPI @"0000"
#define DEFAULT_IDENTITY_PASSWORD @""

// Network
#define DEFAULT_NETWORK_REGISTRATION_TIMEOUT 1800
#define DEFAULT_NETWORK_REALM @""
#define DEFAULT_NETWORK_USE_WIFI YES
#define DEFAULT_NETWORK_USE_3G YES
#define DEFAULT_NETWORK_PCSCF_DISCOVERY_USE_DNS NO
#define DEFAULT_NETWORK_PCSCF_DISCOVERY_USE_DHCP NO
#define DEFAULT_NETWORK_PCSCF_HOST @""
#define DEFAULT_NETWORK_PCSCF_PORT 5060
#define DEFAULT_NETWORK_BACKUP_PCSCF_HOST @""
#define DEFAULT_NETWORK_BACKUP_PCSCF_PORT 5060
#define DEFAULT_NETWORK_USE_SIGCOMP NO
#define DEFAULT_NETWORK_TRANSPORT @"udp"
#define DEFAULT_NETWORK_IP_VERSION @"ipv4"
#define DEFAULT_NETWORK_USE_EARLY_IMS NO

// Account
#define DEFAULT_ACCOUNT_REFEREE @""
#define DEFAULT_ACCOUNT_NAME @""
#define DEFAULT_ACCOUNT_NICKNAME @""
#define DEFAULT_ACCOUNT_GENDER 0
#define DEFAULT_ACCOUNT_BIRTHDATE @""
#define DEFAULT_ACCOUNT_EMAIL @""
#define DEFAULT_ACCOUNT_QQ @""
#define DEFAULT_ACCOUNT_SINAWEIBO @""
#define DEFAULT_ACCOUNT_THUMBNAIL UIImagePNGRepresentation([UIImage imageNamed:@"default_head.png"]);


#define DEFAULT_ACCOUNT_EVERLAUNCHED @"everLaunched"
#define DEFAULT_ACCOUNT_FIRSTLAUNCH @"firstLaunch"
#define DEFAULT_ACCOUNT_CEARTDATA @"creatData"

// NAT Traversal
#define DEFAULT_NATT_HACK_AOR_TIMEOUT 2000
#define DEFAULT_NATT_HACK_AOR NO
#define DEFAULT_NATT_USE_STUN NO
#define DEFAULT_NATT_USE_ICE NO
#define DEFAULT_NATT_USE_STUN_DISCO NO
#define DEFAULT_NATT_STUN_SERVER @""
#define DEFAULT_NATT_STUN_PORT 3489

// QoS
#define DEFAULT_QOS_PRECOND_BANDWIDTH @"Low"
//#define DEFAULT_QOS_PRECOND_STRENGTH tmedia_qos_strength_t.tmedia_qos_strength_none.toString()
//#define DEFAULT_QOS_PRECOND_TYPE tmedia_qos_stype_t.tmedia_qos_stype_none.toString()
#define DEFAULT_QOS_REFRESHER @"none"
#define DEFAULT_QOS_SIP_SESSIONS_TIMEOUT 600000
#define DEFAULT_QOS_SIP_CALLS_TIMEOUT 3600
#define DEFAULT_QOS_USE_SESSION_TIMERS NO

// Media
#define DEFAULT_MEDIA_CODECS -1
#define DEFAULT_MEDIA_CODEC_USE_G722 NO
#define DEFAULT_MEDIA_CODEC_USE_G729AB YES
#define DEFAULT_MEDIA_CODEC_USE_AMR_NB_OA NO
#define DEFAULT_MEDIA_CODEC_USE_AMR_NB_BE NO
#define DEFAULT_MEDIA_CODEC_USE_GSM NO
#define DEFAULT_MEDIA_CODEC_USE_PCMA YES
#define DEFAULT_MEDIA_CODEC_USE_PCMU YES
#define DEFAULT_MEDIA_CODEC_USE_SPEEX_NB YES
#define DEFAULT_MEDIA_CODEC_USE_SPEEX_WB YES
#define DEFAULT_MEDIA_CODEC_USE_SPEEX_UWB YES
#define DEFAULT_MEDIA_CODEC_USE_VP8 NO
#define DEFAULT_MEDIA_CODEC_USE_H263 NO
#define DEFAULT_MEDIA_CODEC_USE_H263P NO
#define DEFAULT_MEDIA_CODEC_USE_H264BP10 NO
#define DEFAULT_MEDIA_CODEC_USE_H264BP20 NO
#define DEFAULT_MEDIA_CODEC_USE_H264BP30 NO
#define DEFAULT_MEDIA_CODEC_USE_THEORA NO
#define DEFAULT_MEDIA_CODEC_USE_MP4VES NO

#define DEFAULT_MEDIA_AUDIO_RESAMPLER_QUALITY 0
#define DEFAULT_MEDIA_AUDIO_CONSUMER_GAIN 0 // disabled
#define DEFAULT_MEDIA_AUDIO_PRODUCER_GAIN 0 // disabled
#define DEFAULT_MEDIA_AUDIO_CONSUMER_ATTENUATION 1.f // disabled
#define DEFAULT_MEDIA_AUDIO_PRODUCER_ATTENUATION 1.f // disabled

// Security
#define DEFAULT_SECURITY_IMSAKA_AMF @"0x0000"
#define DEFAULT_SECURITY_IMSAKA_OPID @"0x00000000000000000000000000000000"
#define DEFAULT_SECURITY_SSL_FILE_KEY_PRIV @""
#define DEFAULT_SECURITY_SSL_FILE_KEY_PUB @""
#define DEFAULT_SECURITY_SSL_FILE_KEY_CA @""
#define DEFAULT_SECURITY_DEVICE_TOKEN @""

// XCAP
#define DEFAULT_XCAP_ENABLED NO
#define DEFAULT_XCAP_ROOT @"http://weicall.net:8080/services"
#define DEFAULT_XCAP_USERNAME @"sip:support@cloudcall.hk"
#define DEFAULT_XCAP_PASSWORD @""

// RCS (Rich Communication Suite)
#define DEFAULT_RCS_AVATAR_PATH @""
#define DEFAULT_RCS_USE_BINARY_SM NO 
#define DEFAULT_RCS_CONF_FACT @"sip:Conference-Factory@cloudcall.hk"
#define DEFAULT_RCS_FREE_TEXT @"Hello world"
#define DEFAULT_RCS_HACK_SMS NO
#define DEFAULT_RCS_USE_MSRP_FAILURE YES
#define DEFAULT_RCS_USE_MSRP_SUCCESS NO
#define DEFAULT_RCS_USE_BINARY_SMS NO
#define DEFAULT_RCS_USE_MWI NO
#define DEFAULT_RCS_USE_OMAFDR NO
#define DEFAULT_RCS_USE_PARTIAL_PUB NO
#define DEFAULT_RCS_USE_PRESENCE NO
#define DEFAULT_RCS_USE_RLS NO
#define DEFAULT_RCS_SMSC @"sip:+8612345678901@cloudcall.hk"
// static const NgnPresenceStatus DEFAULT_RCS_STATUS NgnPresenceStatus.Online
#define DEFAULT_RCS_AUTO_ACCEPT_PAGER_MODE_IM YES

//smstext,sharetext
#define GROUPCALL_SMS_TEXT @"groupcall_sms_text"
#define GROUPCALL_SHARE_TEXT @"groupcall_share_text"
#define INVITE_SHARE_TEXT @"invite_share_text"

//show new Function
#define SHOW_NEW_FUNCTION_REMIND @"ShowNewFeatureRemind"
#define SHOW_NEW_FOR_SHAKE_TO_SIGNIN @"ShakeToSignInViewController"
#define SHOW_NEW_FOR_PERSONALINFO @"PersonalInfoNewViewController"
#define SHOW_NEW_FOR_SLOTMACHINE @"SlotMachineViewController"
//#define SHOW_NEW_FOR_GROUP @"Group"
//#define SHOW_NEW_FOR_GROUPCALL @"GroupCall"

//#define NOTIFICATION_ICON_BADGE @"NotificationIconBadge"

#define IS_SCREEN_4_INCH	([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(640, 1136), [[UIScreen mainScreen] currentMode].size) : NO)
#define IS_SCREEN_35_INCH	([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(640, 960), [UIScreen mainScreen].currentMode.size) :NO) || ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(320, 480), [UIScreen mainScreen].currentMode.size) :NO)
#define IS_IPAD [[[UIDevice currentDevice] model] rangeOfString:@"iPad" options:NSCaseInsensitiveSearch].length>0


#endif /* NGNCONFIGURATIONENTRY_H */
